### ISSUE TITLE
utf-8 support

### ISSUE THREAD

**Issue by franciscocosta** [mankyd/htmlmin#11]
It is not possible to parse this:

```htmlmin.minify('<a href="http://example.com/?a=1&b=2" title="Tomé">Tomé</a>')```

**Comment by cdown** [comment]
+1

**Comment by mankyd** [comment]
Are you using Python 2.x? If so, the following works fine for me. Note the 'u' prefix:

    >>> htmlmin.minify(u'<a href="http://example.com/?a=1&b=2" title="Tomé">Tomé</a>')
    u'<a href="http://example.com/?a=1&amp;b=2" title=Tom\xe9>Tom\xe9</a>'

Similarly, in Python3, it works just fine:

    >>> htmlmin.minify('<a href="http://example.com/?a=1&b=2" title="Tomé">Tomé</a>')
    '<a href="http://example.com/?a=1&amp;b=2" title=Tomé>Tomé</a>'

**Comment by cdown** [comment]
Sorry, I should have provided a direct example of my use, which is from the command line, not from the Python API. Specifically, the following snippet works with Unicode in Python 3.4.3, but not in 2.7.9. It seems that stdin is being decoded using `ascii`, even in locales with Unicode support:

    % locale
    LANG=en_GB.UTF-8
    LC_CTYPE="en_GB.UTF-8"
    LC_NUMERIC="en_GB.UTF-8"
    LC_TIME="en_GB.UTF-8"
    LC_COLLATE=C
    LC_MONETARY="en_GB.UTF-8"
    LC_MESSAGES="en_GB.UTF-8"
    LC_PAPER="en_GB.UTF-8"
    LC_NAME="en_GB.UTF-8"
    LC_ADDRESS="en_GB.UTF-8"
    LC_TELEPHONE="en_GB.UTF-8"
    LC_MEASUREMENT="en_GB.UTF-8"
    LC_IDENTIFICATION="en_GB.UTF-8"
    LC_ALL=
    % htmlmin -s -c <<< '你好'                                                           
    Traceback (most recent call last):
      File "/tmp/ee/venv2/bin/htmlmin", line 9, in <module>
        load_entry_point('htmlmin==0.1.5', 'console_scripts', 'htmlmin')()
      File "/tmp/ee/venv2/lib/python2.7/site-packages/htmlmin/command.py", line 157, in main
        minifier.input(line)
      File "/tmp/ee/venv2/lib/python2.7/site-packages/htmlmin/main.py", line 165, in input
        self._parser.feed(i)
      File "/usr/lib64/python2.7/HTMLParser.py", line 117, in feed
        self.goahead(0)
      File "/usr/lib64/python2.7/HTMLParser.py", line 155, in goahead
        if i < j: self.handle_data(rawdata[i:j])
      File "/tmp/ee/venv2/lib/python2.7/site-packages/htmlmin/parser.py", line 287, in handle_data
        data = whitespace_re.sub(' ', data)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)

**Comment by mankyd** [comment]
Ah, sorry about that. Should be fixed in b3ad76593fd74b4666177f923da375cb03744093. I will work on getting a new release out sometime soon.
