### ISSUE TITLE
">" incorrectly transformed as >

### ISSUE THREAD

**Issue by plyd** [mankyd/htmlmin#32]
<input value=">"> is transformed in <input value=>> which is not good HTML.

**Comment by mankyd** [comment]
Howdy. This sounds like a bad issue. Can you  provide me with a sample where there problem occurs?

**Comment by plyd** [comment]
Hello mankyd,
Thanks for your answer!
Here is a small example I wrote with this bug :

#!/usr/bin/python2.7
import htmlmin

example_page = u"""<html><body>
<form>
Click on the button to submit <input type="submit" value=">" />
</form>
</body></html>"""

minified_example = htmlmin.minify(example_page)
print minified_example
#  returns:
#  <html><body> <form> Click on the button to submit <input type=submit value=>> </form> </body></html>
