### ISSUE TITLE
Removes quotes when attribute value contains =

### ISSUE THREAD

**Issue by avacariu** [mankyd/htmlmin#33]
Example:

```
In [3]: htmlmin.minify('<meta name="viewport" content="width=device-width">')
Out[3]: '<meta name=viewport content=width=device-width>'
```

The output is invalid since you can't have an = in an unquoted attribute value.

The fix is just to add `or '='  in val` to https://github.com/mankyd/htmlmin/blob/master/htmlmin/escape.py#L64

I'll create a PR with the fix + some tests.

**Comment by plyd** [comment]
looks very similar to bug 32.
your fix could be extended to all the chars that are not accepted alone without quotes (like ">")

**Comment by vlad003** [comment]
I didn't realize that's what that bug was about. I'll commit a fix that includes all the invalid characters.
