### ISSUE TITLE
Inconsistent behaviour between Python 2 & 3 with unicode whitespaces

### ISSUE THREAD

**Issue by Totktonada** [mankyd/htmlmin#39]
Python 3 has re.UNICODE flag set by default, so `\w`, `\s` and so on works in the another way than in Python 2. In case when htmlmin used with Python 3 all non-breaking, thin and other unicode whitespaces (utf-8 encoded, not html entity) replaced with the regular whitespace. This behaviour certainly unexpected by a user.

I tried to replace `\s` in `whitespace_re` definition with `[ \t\n\r\f\v]` (according to the `re` module docs) and it seems working good for my case (non-breaking spaces whitepaces inside a text, not btw tags). But it possibly doesn’t handle all possible cases of such differences.

**Comment by mankyd** [comment]
I believe that this is fixed in a recent checkin. I no longer rely on `\s` or the likes. All space characters are now explicitly listed in the regexes.

A new release will be out soon. Please reopen if the issue persists.
