### ISSUE TITLE
Issues with minifying br-tag

### ISSUE THREAD

**Issue by Kyrremann** [mankyd/htmlmin#47]
I just started using you're plugin, and noticed that it strips off the `/` in `<br/>` tags. This is an issue for me, as I'm validating `xhtml`

```python
import htmlmin

test_string = """
<strong>hello world</strong>
<br />
<strong>hello earthling</string>
"""

print(htmlmin.minify(test_string))
```

```bash
$ python test.py 
 <strong>hello world</strong> <br> <strong>hello earthling</string>
```

I'm guessing/hoping it is not intended behaviour?

**Comment by mankyd** [comment]
This is intended. This library does not support XHTML by design.
