### ISSUE TITLE
Regarding updates

### ISSUE THREAD

**Issue by shawnngtq** [mankyd/htmlmin#61]
Hi guys,

This is one of the few Python HTML Minifier. I see it has been close to 4 years since last commit. I was wondering if it's because there is not much to create / update. Or it's abandon?

If it's abandon, is there any new library you would recommend?

**Comment by mankyd** [comment]
I consider it alive. The html spec hasn't changed in any significant way that would impact htmlmin. I don't know that it ever will, the core syntax of HTML/SGML are fairly well established.

I am always happy to accept patches and cut new releases as needed.
